[package]
name = "gtf-read-rs"
version = "0.1.0"
authors = ["debamitro"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[example]]
name="transcripts_to_python"
